Feature: All Accounts

   Background: Setup Test Generate Token
    * def tokenFeature = callonce read('GenerateToken.feature')
    * def token = tokenFeature.response.token
    Given url "https://tek-insurance-api.azurewebsites.net"
    
    Scenario: Get all accounts 
    
    * def dataGenerator = Java.type('api.data.GenereteData')
    * def autoEmail = dataGenerator.getEmail()
    Given path "/api/accounts/get-all-accounts"
    And header Authorization = "Bearer " + token
    And request
    """
  {
    "id": 7668,
    "email": "autogenerated9831@tekschool.us",
    "title": "Mr.",
    "firstName": "Ali Ahamd",
    "lastName": "Ranzoor",
    "gender": "MALE",
    "maritalStatus": "SINGLE",
    "employmentStatus": "Software Tester",
    "dateOfBirth": "1988-02-27",
    }
    """
    When method get
    Then status 200
    And print response